# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2723f97c78bd5ba4f073748b6cfda0f3810e9910cf98fecdd3e2bef9ac3af67d43841a8ca752b65ea05c59785c848a2279c4d0f07064e1ce652f059a21938d04

test:
  secret_key_base: 4450f6634bcedd2693a22b2c1158a8e70e236a058ddcd81f5769c19c9ec6929a16ed41f1f4e3325ef0631b0ff75400f02a1dfb775e2ee8d40b50cc1b2573fbda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
